version: '3.1'
services:
  app:
      container_name: docker-rumahmakan
      image: rasyidmm/docker-rumahmakan:latest
      build: ./
      ports: 
        - "8080:8080"
      depends_on:
        - dbpostgresql   
      networks:
        - backend
  dbpostgresql:
    container_name: docker-postgres
    image: postgres:12.4
    ports:
      - "5431:5432"
    environment:
      POSTGRES_PASSWORD: locallocal
      POSTGRES_USER: postgres
      POSTGRES_DB: rumahmakanDb
      PGDATA: /var/lib/postgresql/data
    command: ["postgres", "-c", "max_connections=3000", "-c", "shared_buffers=1024MB", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    restart: always
    volumes:
      - pgdata_volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 160s
      timeout: 160s
      retries: 10
    networks:
        - backend
         
networks:
  backend:
    driver: bridge

volumes:
  pgdata_volume:

